### ISSUE TITLE
Error in bookmakers output

### ISSUE THREAD

**Issue by dadee** [Lisandro79/BeatTheBookie#1]
Hi!
First of all, great job guys (and Katia too)!

Did you filtered errors from bookmakers in your research? Here we have that some bookmakers give wrong output - 1/2 is switched I think.

For example, Denmark U17 vs. Andorra U17.

![1](https://user-images.githubusercontent.com/10576773/31990389-68f1aff6-b98e-11e7-9396-ded7b530e99d.png)

**Comment by javkrei** [comment]
Hi! This error came from a change in the format in the websites we crawl to get the data. It should be fixed now, let us know if you see it happening now. Thanks for the feedback!
