### ISSUE TITLE
Handball

### ISSUE THREAD

**Issue by macroy88** [Lisandro79/BeatTheBookie#11]
If I able to pay for you and your team maybe 2-3000$ can you do one system for handball too?
I can give you a free hosting too. It is possible?

**Comment by sashml** [comment]
If you have the data  .. It's worth to try, cool idea

**Comment by macroy88** [comment]
We must find 2 or 3 draw handball games for a day it will be make more than enough profit. What data do you need for it? I have an excel with the matches and ft score since 2015.
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2018. 09. 30., 13:00 Sash <notifications@github.com> wrote:
If you have the data  .. It's worth to try, cool idea

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Lisandro79/BeatTheBookie","title":"Lisandro79/BeatTheBookie","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Lisandro79/BeatTheBookie"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sashml in #11: If you have the data  .. It's worth to try, cool idea"}],"action":{"name":"View Issue","url":"https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425712520"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425712520",
"url": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425712520",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Lisandro79/BeatTheBookie] Handball (#11)",
"sections": [
{
"text": "",
"activityTitle": "**Sash**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sashml",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Lisandro79/BeatTheBookie\",\n\"issueId\": 11,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Lisandro79/BeatTheBookie\",\n\"issueId\": 11\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425712520"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 386109900\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sashml** [comment]
>>I have an excel with the matches and ft score since 2015.
Please attach :)

**Comment by macroy88** [comment]
I will send it asap i am on the way to Austria now.
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2018. 09. 30., 13:13 Sash <notifications@github.com> wrote:


I have an excel with the matches and ft score since 2015.
Please attach :)



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Lisandro79/BeatTheBookie","title":"Lisandro79/BeatTheBookie","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Lisandro79/BeatTheBookie"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sashml in #11: \u003e\u003eI have an excel with the matches and ft score since 2015.\r\nPlease attach :)"}],"action":{"name":"View Issue","url":"https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425713231"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425713231",
"url": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425713231",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Lisandro79/BeatTheBookie] Handball (#11)",
"sections": [
{
"text": "",
"activityTitle": "**Sash**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sashml",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Lisandro79/BeatTheBookie\",\n\"issueId\": 11,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Lisandro79/BeatTheBookie\",\n\"issueId\": 11\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425713231"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 386109900\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Lisandro79** [comment]
Hi, 

I do not have the availability to do this, but Javier might. I have assigned him to this issue. I suppose that he should be able to scrap handball games from the sites, similar to what we did for football games. Please talk to him via private message

Cheers

**Comment by macroy88** [comment]
Ok, I will do it. Thanks
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2018. 09. 30., 14:57 Orsai <notifications@github.com> wrote:
Hi,
I do not have the availability to do this, but Javier might. I have assigned him to this issue. I suppose that he should be able to scrap handball games from the sites, similar to what we did for football games. Please talk to him via private message
Cheers

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Lisandro79/BeatTheBookie","title":"Lisandro79/BeatTheBookie","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Lisandro79/BeatTheBookie"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Lisandro79 in #11: Hi, \r\n\r\nI do not have the availability to do this, but Javier might. I have assigned him to this issue. I suppose that he should be able to scrap handball games from the sites, similar to what we did for football games. Please talk to him via private message\r\n\r\nCheers"}],"action":{"name":"View Issue","url":"https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425719240"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425719240",
"url": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425719240",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Lisandro79/BeatTheBookie] Handball (#11)",
"sections": [
{
"text": "",
"activityTitle": "**Orsai**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Lisandro79",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Lisandro79/BeatTheBookie\",\n\"issueId\": 11,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Lisandro79/BeatTheBookie\",\n\"issueId\": 11\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Lisandro79/BeatTheBookie/issues/11#issuecomment-425719240"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 386109900\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by macroy88** [comment]
How can I write a private message for Javier (JavKrei) I have opened a personal page but there isn't any option for write a pm. I have sent a message on Facebook Messenger here have I found him to first time.

**Comment by javkrei** [comment]
@macroy88 you can send me an email to the address shown in our publication: https://arxiv.org/abs/1710.02824
