### ISSUE TITLE
No advantageous bet opportunities currently available.

### ISSUE THREAD

**Issue by JordanADavies** [Lisandro79/BeatTheBookie#12]
The dashboard is currently showing 'No advantageous bet opportunities currently available.'

Are there no opportunities available or is the site down?

**Comment by Lisandro79** [comment]
Hi Jordan,

The dashboard is down at the moment. We will fix the problem in a day or two. I will let you know once it is functional again

Cheers

**Comment by JordanADavies** [comment]
Awesome. Thank you! Great work btw.

**Comment by JordanADavies** [comment]
Sorry to keep bothering you but is there any update on this?

**Comment by Lisandro79** [comment]
It is working now.

Cheers

**Comment by JordanADavies** [comment]
Thanks, although the away teams odds are not showing.

**Comment by JordanADavies** [comment]
It's back to 'No advantageous bet opportunities currently available.'

**Comment by basiiiil** [comment]
Hi Lisandro!

Thank you for keeping the Dashboard running!
Although since yesterday it seems like it's down again?
