### ISSUE TITLE
One dashboard is down and the other so no data

### ISSUE THREAD

**Issue by IntheDark** [Lisandro79/BeatTheBookie#14]
First I want to thank you for this awesome work, you deserve it.

Second, I'd like to inform that the two dashboard addresses have issues.
• http://35.185.212.121: Is down (connection error)
• http://104.198.69.97: Never shows any bet

**Comment by IntheDark** [comment]
The first one works now.

**Comment by Lisandro79** [comment]
@IntheDark,

http://35.185.212.121 is working now.
http://104.198.69.97 has been shut down permanently

Hope this helps

**Comment by IntheDark** [comment]
@Lisandro79

I suppose that the URLs are inverted, as I can only connect to "http://104.198.69.97". ;-)

Still I have been testing that all day and at no time has returned any results. Only the message "No advantageous bet opportunities currently available."

Two days ago, it didn't show any results while the other address (which was still active) did.

**Comment by Lisandro79** [comment]
@IntheDark 

We will keep the dashboard at http://35.185.212.121. We are having some issues at the moment, but I expect it to be online again late today or tomorrow.

We are going to shut down http://104.198.69.97 (I thought it was already down, but it seems I was wrong). 

Cheers

**Comment by rmechan1994** [comment]
Hello, Lysander, excellent work.
I'd like to know if the dashboard is still active. 
Thank you very much!

**Comment by Lisandro79** [comment]
Hi,

Yes, the dashboard is still active. There are just very few games for now due to the coronavirus crisis. As more games are played around the world, new opportunities should appear on our dashboard.

Cheers

**Comment by rmechan1994** [comment]
Thank you! In which URL is the dashboard active?

**Comment by Lisandro79** [comment]
http://143.89.16.84:9090/

There are many games right being displayed on the dasboard

**Comment by rcarlos1993** [comment]
Hi Lizandro,

Currently the site displays "No advantageous betting opportunities currently available."
Is it true or are there technical problems?

**Comment by Lisandro79** [comment]
The dashboard is working

**Comment by liturregui96** [comment]
Hi Lisandro,
¿Does the dashboard still have the same URL (http://143.89.16.84:9090)?
I get the message "No advantageous bet opportunities currently available", or it is due to the small number of games.

Thank you and greetings!

**Comment by Keokeo33** [comment]
I have more chance to win the bet than you,you lose all the predict of
28/06...

  Υπολογιστικό φύλλο χωρίς τίτλο
<https://docs.google.com/spreadsheets/d/1GvyJCc8OiZciorzim9Zcb7Wi_MR8GykHo4SzPVwdonc/edit?usp=drivesdk>



Στις Σάβ, 27 Ιουν 2020, 14:01 ο χρήστης liturregui96 <
notifications@github.com> έγραψε:
