### ISSUE TITLE
how the data compares with that of the current bookmakers

### ISSUE THREAD

**Issue by colcrt** [Lisandro79/BeatTheBookie#15]
I do not understand is how to compare data from databases with the current and that are presented in the bookmakers today?

**Comment by Lisandro79** [comment]
Hi @colcrt ,

Could you please give us some more details on what do you want to compare?

Cheers

**Comment by colcrt** [comment]
I don't understand how you get the picks of games that will be played in the following hours

**Comment by Lisandro79** [comment]
The strategy is explained in our paper, you will find all the details there. In short, the procedure to choose which bets are advantageous works as follows: we consider some odds as mispriced (and therefore a favorable bet for us) when their value is higher than the mean odds across bookmakers ("higher" here is determined by a threshold).

Hope this helps

Cheers

**Comment by Keokeo33** [comment]
In your formula which odds your using

**Comment by Keokeo33** [comment]
Ii only understant that bet is not luck but real game which are decide from a system algorithm of  football combanies..

**Comment by Keokeo33** [comment]
Y8show us the for.mula with real numbers....

**Comment by WildZes** [comment]
I'd like to append this issue.
If I'm right, strategic code is in src/strategies folder. Is it correct?

Please, give some example how to use it.

**Comment by Keokeo33** [comment]
Μα τι ασχολειστε ειναι ασχετοι

Στις Πέμ, 7 Σεπ 2023, 23:17 ο χρήστης WildZes ***@***.***>
έγραψε:
