### ISSUE TITLE
http://143.89.16.84:9090/ not available

### ISSUE THREAD

**Issue by stokic** [Lisandro79/BeatTheBookie#18]

**Comment by Lisandro79** [comment]
We removed the dashboard. It's no longer available. Sorry about this

**Comment by Lisandro79** [comment]
We've moved it here: http://42.2.153.218:9090/

**Comment by stokic** [comment]
@Lisandro79 thanks for letting me know. great job btw on the paper and the code.

may I ask, did you build your own scrapers for odds or if you've used some api that provides real time odds? I understand if you don't want to answer publicly :)

**Comment by Lisandro79** [comment]
Yes, we built our own scraper. I can answer that publicly, I just cannot share the code for legal reasons

**Comment by stokic** [comment]
Thanks for the answer. Great work, good luck with avoiding bet size restrictions ;)
