### ISSUE TITLE
Dashboard Sites Not Working?

### ISSUE THREAD

**Issue by 95research** [Lisandro79/BeatTheBookie#2]
For at least 48 hours, both of the related sites have displayed the message "No advantageous bet opportunities currently available." Are the sites working but no opportunities have come about or have the sites stopped working? Thank you.

**Comment by Lisandro79** [comment]
We are having some troubles with the dashboard. We will check that soon

**Comment by javkrei** [comment]
@95research , the server on http://184.73.28.182/ has been fixed, thank you for the heads up. Please let us know if any problem arises again.

**Comment by 95research** [comment]
Thanks. I am interested in helping keep the sites available. I am not much
of a coder, but I am willing to contribute resources if that will help.
Thank you. 95research

**Comment by ernadko** [comment]
Dashboard is showing same one advantageous game two days in row and also odds which are shown are changed yesterday.

**Comment by Lisandro79** [comment]
Thanks for telling us. We fixed this today, please let us know again if anything goes wrong.

**Comment by LoriKarikari** [comment]
This problem is occurring again. No opportunities available.

**Comment by Lisandro79** [comment]
The server went down due to the number of visitors. The problem has been fixed now.
