### ISSUE TITLE
What‘s the basis that we assign value to odds_history_series.active?

### ISSUE THREAD

**Issue by wffger** [Lisandro79/BeatTheBookie#3]
The description of "Odds_history_series.**Active**" is: specifies if closing odds were active at closing time, only valid in historical odds database. Can I understand that it was the last value of odds offered by bookies for per match? Thanks :)

**Comment by Lisandro79** [comment]
Yes, that's correct. If "active == 1" then the odd was active at the closing time. If "active == 0" then the odd was not available at closing time and the value is the last one available in the series.

**Comment by wffger** [comment]
Thank you very much!
