### ISSUE TITLE
Both Teams To Score / Under & Over

### ISSUE THREAD

**Issue by macroy88** [Lisandro79/BeatTheBookie#9]
Hi. Your system is very good. It is possible to set up it for BTTS and Under/Over too?

**Comment by Lisandro79** [comment]
Hi,
Yes, in theory it is possible. However: A) we do not have the time / money resources to do this now (we  moved to other projects and we cannot write, upload and maintain new code) and B) although in principle the strategy should work for other types of bets, we haven't empirically tested this hypothesis. To be sure that it works, we need to put more work and time on this (back to point A).

Sorry I cannot be of more help

Cheers

**Comment by macroy88** [comment]
Hi,

thank you for your answer. I AM sorry that you have no more time for this project. I have a question. How can I embed your script on my homepage? Does you have any source therefor?
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2018. 09. 03., 2:31 Orsai <notifications@github.com> wrote:
Hi,
Yes, in theory it is possible. However: A) we do not have the time / money resources to do this now (we  moved to other projects and we cannot write, upload and maintain new code) and B) although in principle the strategy should work for other types of bets, we haven't empirically tested this hypothesis. To be sure that it works, we need to put more work and time on this (back to point A).
Sorry I cannot be of more help
Cheers

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Lisandro79/BeatTheBookie","title":"Lisandro79/BeatTheBookie","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Lisandro79/BeatTheBookie"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Lisandro79 in #9: Hi,\r\nYes, in theory it is possible. However: A) we do not have the time / money resources to do this now (we  moved to other projects and we cannot write, upload and maintain new code) and B) although in principle the strategy should work for other types of bets, we haven't empirically tested this hypothesis. To be sure that it works, we need to put more work and time on this (back to point A).\r\n\r\nSorry I cannot be of more help\r\n\r\nCheers"}],"action":{"name":"View Issue","url":"https://github.com/Lisandro79/BeatTheBookie/issues/9#issuecomment-417971466"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Lisandro79/BeatTheBookie/issues/9#issuecomment-417971466",
"url": "https://github.com/Lisandro79/BeatTheBookie/issues/9#issuecomment-417971466",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Lisandro79/BeatTheBookie] Both Teams To Score / Under \u0026 Over (#9)",
"sections": [
{
"text": "",
"activityTitle": "**Orsai**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Lisandro79",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Lisandro79/BeatTheBookie\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Lisandro79/BeatTheBookie\",\n\"issueId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Lisandro79/BeatTheBookie/issues/9#issuecomment-417971466"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 374952228\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Lisandro79** [comment]
Hi,

I am not sure of what script you are talking about. If you mean the scrapper, then the answer is that you can't embed it into your website. Initially, we intended to upload the scrapper to our github repository, but we found that there are some legal issues with doing so. Sorry I cannot be of more help

Best

**Comment by liturregui96** [comment]
Hi Lisandro,
¿Does the dashboard still have the same URL (http://143.89.16.84:9090)?
I get the message "No advantageous bet opportunities currently available", or it is due to the small number of games.

Thank you and greetings!
